### ISSUE TITLE
Configure cmake to allow building DOtherside with mingw

### ISSUE THREAD

**Issue by richard-ramos** [status-im/dotherside#3]
In order to crosscompile to Windows, we need to define a configuration for cmake that allows using mingw to generate a `.a` library that can be understood by this toolchain.

In https://github.com/status-im/dotherside/tree/mingw I created the file `mingw-w64-x86_64.cmake`, to be used (unsuccessfully) like this:
```
mkdir -p build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=~/mingw-w64-x86_64.cmake -DCMAKE_BUILD_TYPE=Release .. 
make DOtherSide
```

**Comment by richard-ramos** [comment]
Update: the branch seems to work (assuming you have SDL2 dev files and mingw-64 installed)

**Comment by iurimatias** [comment]
old issue
